#!/bin/zsh
# Creates simple rectange of default width 256, default height 128.
# Puts optional text in the center, and allows an optional
# filename (defaults to ./foo.svg).
# Takes optional width, height, and text parameters, e.g.
# svgrecttxt 648 480 "IMAGE GOES HERE" box.svg
WIDTH=256
HEIGHT=128
TEXT=""
FILENAME="./foo.svg"
[ $1 ] && WIDTH=$1
[ $2 ] && HEIGHT=$2
[ $3 ] && TEXT=$3
[ $4 ] && FILENAME=$4
cat <<EOF > $FILENAME
<svg width='$WIDTH' height='$HEIGHT' xmlns='http://www.w3.org/2000/svg' version='1.1' >
<rect width="${WIDTH}" height="${HEIGHT}"  fill="lightgray" stroke="gray" stroke-width=".2"/>
<text text-anchor="middle" x="50%" y="50%" dy=".35em" font-family="sans-serif" font-size="24px" fill="black">$3</text> 
</svg>
EOF
echo "Created file ${FILENAME}"
