#!/bin/zsh
# Appends to a log file if you type a message, or
# just brings up vim in case you want to log several
# lines' worth
# Nothing added to command line, so just bring up vim:

# Replace this with the location of the text file
# you wish to use as your log
log_file=~/log.txt

# Alternate way to capture remainder of command line:
# echo "Save this: ${@:1}"
if [ $# -eq 0 ]
  then
    nvim $log_file
else
  # User entered something like this:
  #   edlog Extra backup last night due to OS update
  # echo "Save this: ${@:1}"
  # Alternate: LINE="  $*"
  LINE="  ${@:1}"
  # Format date like 07/25/2019
  # Start inserting text after the date.
  # Insert all arguments on command line.
  # Then write out file, and quit back to shell
  nvim -c ":pu=strftime('%m/%d/%Y')" -c ":startinsert!" -c "norm a$LINE" -c "wq" $log_file
fi


